DROP VIEW IF EXISTS vw_OrderReport;
DROP VIEW IF EXISTS vw_PublicCustomers;
GO

DROP USER IF EXISTS eventify_user;
GO

DROP ROLE IF EXISTS EventifyReader;
GO

DROP TABLE IF EXISTS OrderRows;
DROP TABLE IF EXISTS Payments;
DROP TABLE IF EXISTS Tickets;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Venues;
GO

DROP DATABASE IF EXISTS Eventify;
